const costants = {
    LOGIN: 'login',
    REGISTER: 'register',
    USER: 'user',
    NOTES: 'notes',
    UPDATE: 'update',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',
    USER_UPDATE_RESET: 'USER_UPDATE_RESET',

    CREATE_NOTE_REQUEST: 'CREATE_NOTE_REQUEST',
    CREATE_NOTE_SUCCESS: 'CREATE_NOTE_SUCCESS',
    CREATE_NOTE_FAIL: 'CREATE_NOTE_FAIL',
    RESET_NOTE: 'RESET_NOTE',

    GET_NOTES_REQUEST: 'GET_NOTES_REQUEST',
    GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
    GET_NOTES_FAIL: 'GET_NOTES_FAIL',

    GET_NOTE_REQUEST: 'GET_NOTE_REQUEST',
    GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',
    GET_NOTE_FAIL: 'GET_NOTE_FAIL',
    GET_NOTES_RESET: 'GET_NOTES_RESET',

    UPDATE_NOTE_REQUEST: 'UPDATE_NOTE_REQUEST',
    UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
    UPDATE_NOTE_FAIL: 'UPDATE_NOTE_FAIL',

    DELETE_NOTE_REQUEST: 'DELETE_NOTES_REQUEST',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTES_SUCCESS',
    DELETE_NOTE_FAIL: 'DELETE_NOTES_FAIL',


}

export default costants;